Pregunta 1 :
¿Cuántos clientes hay en la tabla clientes?

Respuesta: Para contar el número de clientes en la tabla "clientes", puedes usar la siguiente consulta SQL:

SELECT COUNT (*) AS total_clientes FROM clientes; 

## AS Asigna o renombra el resultado para una mayor entendibilidad 
de la persona que realice la consulta o en el contexto del gerente que reliza la consulta
Mientras que la segunda consulta le asigna un alias "total_clientes".


