Pregunta 5: 

Muestra el nombre, correo y fecha de nacimiento de todos los clientes, ordenados alfabéticamente por nombre.
Respuesta: puedes usar la siguiente consulta SQL

SELECT nombre, correo, fecha_nacimiento from clientes
ORDER by nombre ASC;  

## La consulta selecciona el nombre, correo y fecha de nacimiento de todos los clientes y 
los ordena alfabéticamente por nombre en orden ascendente (ASC).

